### ISSUE TITLE
unlambda: Suggestion for non-pointer receiver method changed behavior

### ISSUE THREAD

**Issue by krishicks** [go-critic/go-critic#1009]
:wave: I came across a suggested change that had to be reverted, as it changed the behavior of the code.

This is the code that triggered an unlambda suggestion: https://github.com/hashicorp/nomad/blob/master/drivers/shared/executor/executor_linux.go#L505

`Process.Wait` isn't owned by us, and does not have a pointer receiver: https://github.com/hashicorp/nomad/blob/dfcdc9c53d71d4accb4f7340048b2c23e040c70a/vendor/github.com/opencontainers/runc/libcontainer/process.go#L85

This results in different behavior when removing the lambda, as you can see here (also includes the same example with a pointer receiver): https://play.golang.org/p/0UDY1mmK5ni

**Comment by quasilyte** [comment]
Hi!

This false positive is unfortunate. I'm sorry to hear that you had to revert the code.

The fix is on its way: #1008
Although I may re-write it a bit as it looks overly complicated right now.

We should stop giving suggestions for the "methods values" completely.

**Comment by quasilyte** [comment]
Does #1008 solve this issue?
Can this ticket be resolved?

**Comment by krishicks** [comment]
Yep, it fixes it! Tested with 0.5.3.

Thanks!
