### ISSUE TITLE
Syntax errors in gocritic ruleguard file are silently ignored by golangci

### ISSUE THREAD

**Issue by sebastien-rosset** [go-critic/go-critic#1010]
golangci-run silently ignores the following gocritic configuration issues:
1. The value of the `ruleguard/rules` setting is an inexistent path or the file is not readable. For example, the value is `ruleguard/rules.go`, but that file does not exist
2. The content of the ruleguard rules has at least one syntax error. All rules in the rules.go file are silently ignored.

I initially opened https://github.com/golangci/golangci-lint/issues/1565, but after some code review, it looks like the issue is in gocritic.
I see a TODO here:
https://github.com/go-critic/go-critic/blob/master/checkers/ruleguard_checker.go#L52-L74

The log statements are not displayed by gocritic, which makes it non-obvious there is a problem.

**Comment by quasilyte** [comment]
I wonder what would be the better way to handle that situation.

Doing `panic(err)` is the simplest option, but it might be a sloppy solution.

**Comment by sebastien-rosset** [comment]
Is there a way to create a analyzer "issue"?

**Comment by quasilyte** [comment]
Fixed by #1015.
