### ISSUE TITLE
Automate docs publication

### ISSUE THREAD

**Issue by cristaloleg** [go-critic/go-critic#1016]
Currently docs (`overview.md` file to be exact) isn't updated automatically in this repo https://github.com/go-critic/go-critic.github.io but it can be 😄 

To generate new docs you need to run `make docs` from this repo. And then add a PR/commit to the repo mentioned above. Looks like this can be automated via Github Actions, slightly hacky but should work https://github.community/t/triggering-by-other-repository/16163/4

**Comment by Lasiar** [comment]
Diagram from https://github.com/go-critic/go-critic/pull/1375
<details>
  <summary>Duplicate diagram</summary>
<img width="1404" alt="image" src="https://github.com/go-critic/go-critic/assets/31652715/bb526311-a9b3-4c90-acc2-99ae29e8df5e">
</details>


There were two ways:
1. Send file via dispatches
props: simple
cons: limit of size of file

2. Checkout this repo in actions of https://github.com/go-critic/go-critic.github.io and copy file
props: no limit
cons: need another token
cons:  job takes longer to complete



I chose the first option.
