### ISSUE TITLE
ifElseChain code not changeable

### ISSUE THREAD

**Issue by Bysmyyr** [go-critic/go-critic#1017]
Hi, following code snippet gives "ifElseChain: rewrite if-else to switch statement (gocritic) if v := recover(); v != nil {"

We do not see how switch can make it clearer.

```
func t(f func() error) {
	err := f
	defer func() {
		if v := recover(); v != nil {
			panic(v)
		} else if err != nil {
			errors.New("asd")
		} else {
			errors.New("asdad")
		}
	}()
	return

}

**Comment by cristaloleg** [comment]
Hi, probably something like this:

```go
func t(f func() error) error {
	err := f()
	defer func() {
		switch v := recover(); {
		case v != nil:
			panic(v)
		case err != nil:
			err = errors.New("asd")
		default:
			err = errors.New("asdad")
		}
	}()
	return err
}
```

Also this can be made in a simpler way due to redundant `else`:
```go

func t(f func() error) error {
	err := f()
	defer func() {
		if v := recover(); v != nil {
			panic(v)
		}
		if err != nil {
			err = errors.New("asd")
		} else {
			err = errors.New("asdad")
		}
	}()
	return err
}
```

But anyway it's up to you, this check is more about style rather than bugs or unclear code.

**Comment by quasilyte** [comment]
As @cristaloleg said, this checker is quite opinionated.

It makes an assumption that usually if/elseif chains can be either rewritten (Oleg gave an example)
or rewritten as switch statement (which is a preferred Go way to write if-elseif statements).

**Comment by Bysmyyr** [comment]
Ok, thanks.
