### ISSUE TITLE
Suggesting typeUnparen when not equivalent

### ISSUE THREAD

**Issue by bruno-anjos** [go-critic/go-critic#1035]
I stumbled upon this suggestion:

```
typeUnparen: could simplify (<-chan *WebsocketMsg) to <-chan *WebsocketMsg (gocritic)
```

for this line:

```
messagesQueue := make(chan (<-chan *WebsocketMsg), 10)
```

From what i saw in the go documentation this is not right since the arrow is applied to the leftmost type
([see ](https://golang.org/ref/spec#Channel_types))

There it says the following

```
The <- operator associates with the leftmost chan possible:

chan<- chan int    // same as chan<- (chan int)
chan<- <-chan int  // same as chan<- (<-chan int)
<-chan <-chan int  // same as <-chan (<-chan int)
chan (<-chan int)
```

And therefore if i remove the parenthesis i would go from a channel of receive-only channels to a send-only channel of channels. Can you please confirm i might be missing something.

**Comment by quasilyte** [comment]
Interesting case!
Thank you for reporting this.
I'll try to roll a solution in the near time.
(If nobody beats me to it.)
