### ISSUE TITLE
lint/big-copy_checker: also checks function calls

### ISSUE THREAD

**Issue by fexolm** [go-critic/go-critic#110]

**Comment by Quasilyte** [comment]
What about this: only check for function signatures, detect parameters bigger than X (probably >=48 byte) and report them?
It's better than emitting warnings for each call site, at least in my opinion.

We could also visit closures inside functions and check their signatures.

And I don't think it should be addition to `big-copy` checker.
It will be renamed to `range-value-copy` checker soon.
New checker should be called `big-param` checker.

**Comment by Quasilyte** [comment]
Rationale for checker: `performance`.
