### ISSUE TITLE
A new performance check: prefer operator comparisons to strings.Compare

### ISSUE THREAD

**Issue by go101** [go-critic/go-critic#1167]
The current implementation of the `strings.Compare` function is not efficient, in a some deliberate way.
refs:
* https://github.com/golang/go/issues/50167
* https://github.com/golang/go/issues/50209

At least, for non-three-way comparisons, using operators to compare strings is always faster than using the `strings.Compare` function.

**Comment by peakle** [comment]
@go101 
you can try to open pr to https://github.com/quasilyte/go-perfguard with optimization rule like:
```m.Match(`strings.Compare($_, $_)`).Report(`strings.Compare in hot path`)```


contribution guide: https://github.com/quasilyte/go-perfguard/blob/master/_docs/CONTRIBUTING.md

**Comment by quasilyte** [comment]
I would add them to go-critic though.
go-critic is something that is more useful for most users.
perfguard is an experiment that has ~0 integrations.

**Comment by quasilyte** [comment]
By the way.

@go101 thank you for your books. :heart:

**Comment by peakle** [comment]
@quasilyte can be closed as i see

**Comment by quasilyte** [comment]
I think that we haven't implemented all of the suggested patterns.
Some of them can't be expressed in ruleguard rules beautifully, so maybe someone would like to create a separate checker for that.
