### ISSUE TITLE
add feature for skip/ignore specific ruleguard rules in gocritic/golangci-lint

### ISSUE THREAD

**Issue by peakle** [go-critic/go-critic#1176]
the feature is now available via ruleguard as I know

**Comment by quasilyte** [comment]
I think we need to add new `ruleguard` checker args that would map to a ruleguard rules filters.
Maybe `-enable` + `-disable` flags are enough.
https://github.com/quasilyte/go-ruleguard/blob/9ecd0493f945a154508a8fddb7136d7f3793348e/analyzer/analyzer.go#L194-L211
