### ISSUE TITLE
add feature for quick fix by suggest block in ruleguard rules for gocritic/golangci-lint

### ISSUE THREAD

**Issue by peakle** [go-critic/go-critic#1179]
the functionality is now available for ruleguard binary as i know

**Comment by quasilyte** [comment]
Hmm. I see that there is a QuickFix field in the `linter.Warning` object.
If golangci uses these, it should be able to apply them easily (they're compatible with go/analysis "suggestions").
See also: `WarnFixable()` method of `CheckerContext`.

**Comment by peakle** [comment]
@quasilyte as i see we can close issue, right?

**Comment by quasilyte** [comment]
I believe so, yes.
