### ISSUE TITLE
Support generics for Go 1.18

### ISSUE THREAD

**Issue by cristaloleg** [go-critic/go-critic#1193]
Currently no one have verified does go-critic work with generics from Go 1.18. Probably we should invest time into that.

See https://github.com/golang/go/issues/50558

CC: @quasilyte

**Comment by quasilyte** [comment]
Since we're using ruleguard for some checkers and it uses gogrep inside, I think we should do it in this order:

1. Make gogrep support generics
2. Make ruleguard support generics
3. Make go-critic support generics

**Comment by hu13** [comment]
I ran into a panic error today with v0.6.2

```
/Users/runner/work/drive/drive/drive-repo/bin/golangci-lint run --config golangci.yml ./filesync_daemon/...
panic: load embedded ruleguard rules: rules/rules.go:13: can't load fmt

goroutine 1 [running]:
github.com/go-critic/go-critic/checkers.init.22()
	github.com/go-critic/go-critic@v0.6.2/checkers/embedded_rules.go:46 +0x4b4
make: *** [lint] Error 2

**Comment by shogo82148** [comment]
I have same issue, and found related issues:

- https://github.com/go-critic/go-critic/issues/1157
- https://github.com/golangci/golangci-lint/issues/2414

**Comment by ldez** [comment]
Hello,
I tested go-critic (as a lib through golangci-lint), I detected 3 rules that don't work with generics: `hugeParam`, `rangeValCopy`, `typeDefFirst`.

https://github.com/golangci/golangci-lint/issues/2649

**Comment by quasilyte** [comment]
What is done so far:

- [x] astcopy
- [x] astequal
- [x] gogrep

I've used `typeparams` polyfill package to avoid a Go 1.18 version bump everywhere.

The next step would be making ruleguard adjusted for generics. That would be more complicated.

After that, there should be no problems to make go-critic fully Go 1.18-friedly.

Note that if you build go-critic and golangci-lint from sources (latest branch), it should work for Go 1.18 even today, but go-critic and ruleguard may unpredictably handle generic code.

**Comment by ShayNehmad-RecoLabs** [comment]
Thanks for all the updates! We have some samples with golangci-lint + gocritic that don't work - will proding those help move this ticket forward?

**Comment by cristaloleg** [comment]
@EwenQuim have you built `go-critic` from the latest master?

**Comment by EwenQuim** [comment]
My bad I downloaded gocritic with `go install github.com/go-critic/go-critic/cmd/gocritic@latest` but as the latest release is quite old and there has been no release since the 0.6.3, it was not a correct version.

I installed with `go install github.com/go-critic/go-critic/cmd/gocritic@dfd27d0df92629db2ef1c3958ae695e5132c066c` (latest commit) and it works fine now. Sorry for the inconvenience.

**Comment by pierrre** [comment]
Is it planned to tag a new release, so we can update it in golangci-lint ?

**Comment by cristaloleg** [comment]
^^^ @quasilyte

**Comment by pierrre** [comment]
I still have this issue https://github.com/go-critic/go-critic/issues/1219 with go-critic v0.6.4

**Comment by yabanci** [comment]
Seems like https://github.com/go-critic/go-critic/pull/1239 fixed a bunch of the rules in v0.6.4. What rules are left that are not generics compliant as of now?

**Comment by pierrre** [comment]
I don't know.
https://github.com/golangci/golangci-lint/issues/3136
I'm running all with rules enabled.
Is there a way to check which rule is causing the panic ?

**Comment by powerman** [comment]
> Is there a way to check which rule is causing the panic ?

Try to read whole text of panic and look for familiar rule names - often it's there, just hard to spot.

**Comment by pierrre** [comment]
According to my log: https://github.com/golangci/golangci-lint/issues/3136#issuecomment-1226010507
It's related to ruleguard: https://github.com/go-critic/go-critic/blob/v0.6.4/checkers/embedded_rules.go#L98

**Comment by pierrre** [comment]
Should I report this issue to ruleguard ?

**Comment by pierrre** [comment]
I've found the embedded rule that is causing the panic: externalErrorReassign
https://github.com/go-critic/go-critic/blob/d9c2d892212c6c2b299c784d1c32020d725863d2/checkers/rules/rules.go#L727-L731

**Comment by pierrre** [comment]
New issue https://github.com/go-critic/go-critic/issues/1253

**Comment by quasilyte** [comment]
I believe that the latest release should solve most of the issues.
Hopefully. :sweat_smile:
