### ISSUE TITLE
hugeParam-ref and rangeValCopy default limit is extremely low

### ISSUE THREAD

**Issue by Bysmyyr** [go-critic/go-critic#1200]
I know this rule has a lot of opinions if it is reasonable at all but the current default 80byte limit is newer good. Pointers are already almost the same size and there is a lot of overhead on them. I know everyone using that linter should think this carefully but why not put the default limit much higher like 80000 bytes or something. 

related: https://medium.com/@vCabbage/go-are-pointers-a-performance-optimization-a95840d3ef85

**Comment by quasilyte** [comment]
> like 80000 bytes or something

Well, that's quite a lot.

I would be OK with something around 512 bytes.

> related: https://medium.com/@vCabbage/go-are-pointers-a-performance-optimization-a95840d3ef85

Please note that most people forget that you don't have to make a heap allocated object to pass a big object as a pointer.
```
var big Big
f(&big) // no heap allocations, unless f makes argument escape
```

Passing big objects makes stack frames bigger, it makes register args passing harder and it usually involves calls to memcopy routines (not that fast). GC can be troubled with long-living pointers, when you have many interconnected pointers and structs with many pointers. Passing a local pointer to a function for the time of its call doesn't add a lot of pressure to the GC.

Passing a local pointer is cheap and effective. If you need to copy the data you can dereference the pointer inside a function.

**Comment by Bysmyyr** [comment]
Yeah, I know that(and tried to imply it already but looks like failed) just trying to get things better.

**Comment by Bysmyyr** [comment]
thanks for great software!

**Comment by quasilyte** [comment]
Another good note: https://gist.github.com/teivah/a32a8e9039314a48f03538f3f9535537#gistcomment-3541604

> Notice that the issue is with returning a pointer, not with passing a pointer. Passing the pointer is indeed faster than passing the value, as expected. This discrepancy is likely the effect of having to escape the pointer's data to the heap.

**Comment by cristaloleg** [comment]
I will close this issues 'cause it looks like a discussion. This check isn't enabled (and probably will not be) by default. Thanks.
