### ISSUE TITLE
ITP: linter to enforce named / unnamed result parameters [intent-to-provide]

### ISSUE THREAD

**Issue by leonklingele** [go-critic/go-critic#1201]
I maintain a linter which enforces the use of named / unnamed result parameters: https://github.com/leonklingele/funcresult
Unfortunately, it did not find its way to golangci-lint — was rejected: https://github.com/golangci/golangci-lint/pull/2526#issuecomment-1023715191

Would you be willing to accept a linter which provides such functionality?

**Comment by quasilyte** [comment]
I'm not sure either of these options can be followed consistently across a real code base.

Suppose that you want to avoid the named results at all costs. Then you'll have a problem when you want to override the return value from the deferred call. It's useful in combination with `recover()`. You can catch a panic and assign some error to the output parameter.

Using the named results all the time looks just too weird. In my experience, people tend to use them only in a few situations. The one is already mentioned above and another one is when your return values are not self-explanatory.

There is also an [unnamedResult](https://go-critic.com/overview.html#unnamedResult-ref) checker that does a somewhat similar check.

**Comment by leonklingele** [comment]
> I'm not sure either of these options can be followed consistently across a real codebase.

For me personally, the linter is useful to prevent accidentally-named-result-params. When named result params are needed from time to time, there's always the option to whitelist them with a `nolint` comment, which can easily be grep-ed for.
So it's more about setting a general coding standard than strictly enforcing some coding style.

**Comment by quasilyte** [comment]
Don't get me wrong, I'm not saying that this idea shouldn't exist.
But it doesn't seem to fit go-critic well enough.
It does fit some very strict custom rules for a specific team though.

We have an extension point via https://github.com/quasilyte/go-ruleguard to allow such very opinionated, team-specific checks. It's possible to express funcresult linter in most cases, but it'll be a little bit awkward.

**Comment by leonklingele** [comment]
Part of https://github.com/golangci/golangci-lint/pull/2701.
