### ISSUE TITLE
httpNoBody and golangci-lint run --fix 

### ISSUE THREAD

**Issue by ghostiam** [go-critic/go-critic#1203]
https://github.com/go-critic/go-critic/blob/master/checkers/testdata/httpNoBody/positive_tests.go

after fixing, nil is incorrectly replaced:

```
func badCases() {
	_, _ = http.NewRequest("GET", "https://some.url.com/", http.NewRequest("GET", "https://some.url.com/", http.NoBody))
//                                                             ^^^^^^^
	_, _ = http.NewRequestWithContext(context.TODO(), "GET", "https://some.url.com/", http.NewRequestWithContext(context.TODO(), "GET", "https://some.url.com/", http.NoBody))
//                                                                                        ^^^^^^^
}

```

**Comment by cristaloleg** [comment]
Looks like it replaces with a whole string instead of a body:
https://github.com/go-critic/go-critic/blob/master/checkers/rules/rules.go#L120
& https://github.com/go-critic/go-critic/blob/master/checkers/rules/rules.go#L122

**Comment by quasilyte** [comment]
Ah, yes.
`At()` restricts the replacement too.
We probably need to remove `At()` there.

**Comment by uhthomas** [comment]
Also saw this today. Any idea when we could get this fix merged?

```
edit (off 13155, end 13158): nil -> http.NewRequest(http.MethodGet, "http://fake.net", http.NoBody)
```

<img width="1205" alt="Screenshot 2022-05-30 at 12 08 03" src="https://user-images.githubusercontent.com/9749173/170979959-d5fa7f68-779c-4766-8947-6e329a9b8f9a.png">
