### ISSUE TITLE
Update logrusorgru version

### ISSUE THREAD

**Issue by GENDAAA** [go-critic/go-critic#1206]
Faced with the problem of using go-critic in the company because of the WTFPL license logrusorgru/aurora. Starting with version 2.0.1 they updated the license.
Could you please update the version of this library?

**Comment by quasilyte** [comment]
I wonder if we actually need to use logrus at all.

Maybe we're better off replacing it with some simpler logging (stdlib + maybe ansi colors support)?

CC @cristaloleg
