### ISSUE TITLE
panic under Go 1.18

### ISSUE THREAD

**Issue by eccles** [go-critic/go-critic#1210]
I upgraded y repo to install Go 1.18.
I use golangci-lint and executing:

         golangci-lint --version

now reports:

      panic: load embedded ruleguard rules: rules/rules.go:13: can't load fmt

      goroutine 1 [running]:
      github.com/go-critic/go-critic/checkers.init.22()
        	github.com/go-critic/go-critic@v0.6.2/checkers/embedded_rules.go:46 +0x4b4

**Comment by quasilyte** [comment]
Dup of #1126 #1193 #1157

It could be related to the updated in the Go analysis-related libraries.

Due to the things that are happening in the world right now it's hard to keep up the pace and investigate this issue.
