### ISSUE TITLE
ifElseChain with multiple return value assignment

### ISSUE THREAD

**Issue by atombender** [go-critic/go-critic#1215]
Original code:

```go
var status string
if e, ok := err.(*dingbat.Error); ok {
	status = strconv.Itoa(e.Status)
} else if err != nil {
	status = "ERROR"
} else {
	status = "200"
}
```

Fails with:

```
main.go:278:2: ifElseChain: rewrite if-else to switch statement (gocritic)
	if e, ok := err.(*dingbat.Error); ok {
	^
```

It's not possible to rewrite this into a more legible-looking switch. For example, I do not think this is better:

```go
var status string
switch e, ok := err.(*dingbat.Error); {
case ok:
	status = strconv.Itoa(e.Status)
case err != nil:
	status = "ERROR"
default:
	status = "200"
}
```

I ended up refactoring into a function, but I feel like the original code was just fine.

Tested with 0.6.2.

**Comment by quasilyte** [comment]
I'm surprised that ifElseChain still triggers on something like this.
If memory serves, we had this kind of issue before and in my memory it was fixed.

I agree that assignments in if/else chain require some special attention. We should make ifElseChain skip if/else chains if it contains init clauses.
