### ISSUE TITLE
Transform `init` function in `embedded_rules.go` to an exported function

### ISSUE THREAD

**Issue by ldez** [go-critic/go-critic#1218]
Hello,

I know that my request is really specific to golangci-lint, and if you don't want to do that I will understand.

I know that golangci-lint users come here and open a lot of time the same issue about the panic related to an `init` function (#1210)

I also understand that the problem is not trivial to solve. (#1126)

Currently in golangci-lint, because the `init` function is always called before the `main` (and before the choice of the linters), even if a user doesn't use go-critic, a panic can occur.

If the `init` function in `embedded_rules.go` was not an `init` function but an exported function called into your `main`, in golangci-lint, we'll be able to call it only when the linter is enabled.

Also, I don't know well the design of `go-critic` so maybe this is not possible.

**Comment by andig** [comment]
@quasilyte I've just hit this in golangci-lint and opened false positive issue there. Any chance to look into this request?
