### ISSUE TITLE
release: missing binaries

### ISSUE THREAD

**Issue by ldez** [go-critic/go-critic#1221]
Since v0.6.2, the binaries are missing in the assets releases.
Is it expected?

https://github.com/go-critic/go-critic/releases/tag/v0.6.2
https://github.com/go-critic/go-critic/releases/tag/v0.6.3

**Comment by cristaloleg** [comment]
Looks like a miss on our side, will add tomorrow, thanks for mentioning.

**Comment by cristaloleg** [comment]
Done for both https://github.com/go-critic/go-critic/releases/tag/v0.6.3 & https://github.com/go-critic/go-critic/releases/tag/v0.6.2

Also this will be finally automated https://github.com/go-critic/go-critic/issues/433
