### ISSUE TITLE
lintmain/internal: panic on loading a package ending with _test

### ISSUE THREAD

**Issue by reillywatson** [go-critic/go-critic#1241]
Here's a sample app, that panics on HEAD.

go.mod:
```
module testpkg

go 1.18
```

foo.go:
```
package main

import (
	"fmt"
	"testpkg/foo_test"
)

func main() {
	fmt.Println(foo_test.Foo())
}
```

foo_test/foo_tests.go:
```
package foo_test

func Foo() int {
	return 1
}
```

This panics on trying to sort packages, because loadPackages() adds a nil entry to the package list for foo_test (because it gets loaded as having both an ExternalTest package and a Base package, but Base is nil).

Checking for a nil pkg.Base in loadPackages() (ie https://github.com/reillywatson/go-critic/commit/2a93cf36dea5ee76940228891dbdd548c823fe6d) fixes the panic, but that package really shouldn't be labelled as an external test, it's just a regular package with an unusual name.

**Comment by cristaloleg** [comment]
Oh, sadly I missed this issue. We've moved to https://github.com/go-toolsmith/pkgload recently which doesn't contain this bug (see https://github.com/go-toolsmith/pkgload/blob/0d1cc3a22678e9fb41fae105133acb50c362cf27/pkgload.go#L75).

I'm going to close, sorry for troubles.
