### ISSUE TITLE
embedded ruleguard rule "externalErrorReassign" causes "panic: unreachable"

### ISSUE THREAD

**Issue by pierrre** [go-critic/go-critic#1253]
Original golangci-lint issue (all information is here): https://github.com/golangci/golangci-lint/issues/3136

According to my log: https://github.com/golangci/golangci-lint/issues/3136#issuecomment-1226010507
It's related to ruleguard: https://github.com/go-critic/go-critic/blob/v0.6.4/checkers/embedded_rules.go#L98

I've found the embedded rule that is causing the panic: externalErrorReassign
https://github.com/go-critic/go-critic/blob/d9c2d892212c6c2b299c784d1c32020d725863d2/checkers/rules/rules.go#L727-L731
If I remove this rule ruleguard works well.

I can't try go-critic, because it embeds its own rule.

**Comment by pierrre** [comment]
I have reduced my code to this:
```go
type myType[T any] struct {
	value T
}

func (m *myType[T]) set(v T) {
	m.value = v
}
```

It makes the rule `externalErrorReassign` panic.

**Comment by pierrre** [comment]
After some thoughts, the `$pkg` mentioned in the rule is the `m` in my code.
And `m["pkg"].Object.Is(`PkgName`)` doesn't make any sense, it's not a package name.

Is there a bug in ruleguard ?
Should I open an issue in this project ?

**Comment by cristaloleg** [comment]
@quasilyte is aware of this issue, no need to create new in ruleguard. Thanks for the reduced code!

**Comment by quasilyte** [comment]
I'm going to spend a few hours during this weekend to fix some generics-related issues in gocritic and ruleguard again.
At least this is what I'm hoping to do.

Thank you for the detailed issue description, it really helps. :+1:

**Comment by pierrre** [comment]
For now my quick fix is to disable the `externalErrorReassign` rule.

**Comment by quasilyte** [comment]
This should be fixed now when we'll update the ruleguard version used by gocritic.
