### ISSUE TITLE
redundantSprint false positive with reflect.Value

### ISSUE THREAD

**Issue by pierrre** [go-critic/go-critic#1255]
https://pkg.go.dev/reflect#Value.String
> The fmt package treats Values specially. It does not call their String method implicitly but instead prints the concrete values they hold.

So `fmt.Sprint(v)` is not equivalent to `v.String()` (if `v` is a `reflect.Value`).

https://github.com/go-critic/go-critic/blob/5c89720acc9e12fbbc23d95b381ee3b594762088/checkers/rules/rules.go#L11-L26
Is it possible to exclude `reflect.Value` ?

**Comment by cristaloleg** [comment]
Sounds like `Where(!m["x"].Type.Is(`reflect.Values`))...` should do the trick 🤷
