### ISSUE TITLE
timeCmpSimplify rule is wrong

### ISSUE THREAD

**Issue by ferhatelmas** [go-critic/go-critic#1257]
Rule is wrong because times on the condition can be equal and in this case, not after isn't same with before.

```go
package main

import (
	"fmt"
	"time"
)

func main() {
	t := time.Now()
	fmt.Println(!t.After(t))
	fmt.Println(t.Before(t))
}
```

https://go.dev/play/p/dAY9FXrxzOA

**Comment by quasilyte** [comment]
There is always a small chance of some rule to be wrong.
The case you're describing looks suspicious for me, so I would keep the rule work as is.

Note that you can trick the linter by doing minor code changes or adding a nolint to this exact line.
Or, if you don't like this checker, disable it from the list of gocritic checkers.

**Comment by jkinkead** [comment]
This rule isn't _occasionally_ wrong, it's _always_ wrong. It's suggesting code that fundamentally doesn't do the same thing.

This is analogous to a linter rule that suggests replacing `!(i < 5)` with `i > 5`. It _will_ break code.

**Comment by jkinkead** [comment]
Drilling down, a common type of date math is: Did an event happen in a specific date range?

For example, if I want to determine if a time happened in 2022, using the `time` package, I need to do something like:
```golang
var jan_1_2022 time.Time
var jan_1_2023 time.Time
var dateToCheck time.Time

if !dateToCheck.Before(jan_1_2022) && dateToCheck.Before(jan_1_2023) {
    // Is 2022.
}
```
If these are date-aligned times (meaning, aligned to midnight) - typical for date math - the linter would change this to:
```golang
if dateToCheck.After(jan_1_2022) && dateToCheck.Before(jan_1_2023) {
    // Is 2022 ... except for  Jan 1.
}
```
This logic is now broken, because 1/1/2022 will _not_ be considered as happening in 2022.

**Comment by quasilyte** [comment]
I've read the initial report as something with `t.After(t)`, note the identical `t` argument.
I can't memorize all checkers that well (I'm not the author of all of them), so if false positive report looks suspicious, it doesn't help me much.
It looks like there is an issue and this rule should be either removed or we need to figure out how to improve it (if that's possible).

**Comment by jkinkead** [comment]
Apologies for the tone - too much coffee yesterday. :)

This is a fantastic project and we love it - keep up the great work, and thanks for looking into this! From what I can tell, there isn't a way to make this linter better with the standard Go library, as there isn't something like an `OnOrAfter` function. I'm happy to submit a PR for removing it, if that would be helpful!

**Comment by jufemaiz** [comment]
Just came to add my voice to "this is broken" in the absence of an "equal" addition to the inverse.

That is:

```
!(1 < t) == (t >= 1)
```

not

```
!(1 < t) == (t > 1)
```

as the equality check is skipped in the second example and hence is invalid.
