### ISSUE TITLE
ifElseChain minimum threshold configuration

### ISSUE THREAD

**Issue by borosr** [go-critic/go-critic#1269]
It would be nice if there would be a configuration option to change the default threshold from `2` to bigger value. In some simple case I would appreciate `3` and the simplest way to do it through a configuration param.

**Comment by quasilyte** [comment]
Sounds good to me.
There should an option for that.

**Comment by mcdoker18** [comment]
@quasilyte the issue can be closed because the [PR](https://github.com/go-critic/go-critic/pull/1277) was merged.
