### ISSUE TITLE
Ignore generated files or specific directory?

### ISSUE THREAD

**Issue by tonsV2** [go-critic/go-critic#1313]
Forgive me is this is documented somewhere but is there a way to ignore generated files? I have a bunch of files generated by swagger that I'd like to ignore. This could either be done by ignoring generated files as seen [here](https://github.com/securego/gosec#excluding-generated-files) or ignoring a specific list of directories

**Comment by cristaloleg** [comment]
I see we've `framework/lintmain/internal/check/check.go:130` which should skip that. I will take a look.

As a quick fix you can use `golangci-lint` and ignore generated files by pattern.

**Comment by cristaloleg** [comment]
This PR should fix that, can you check it please? https://github.com/go-critic/go-critic/pull/1327
