### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by ldez** [go-critic/go-critic#1314]
Hello,

As a maintainer of golangci-lint, I want to know if I have to wait for a release before creating a new bug-fix release of golangci-lint.

I think this will be the last bugfix release of v1.51 and I don't want to wait too much.

> We will release `go-critic` next week after a round of review and checks. Sorry for any troubles.

https://github.com/golangci/golangci-lint/issues/2649#issuecomment-1426209576

**Comment by quasilyte** [comment]
https://github.com/go-critic/go-critic/releases/tag/v0.6.6

**Comment by ldez** [comment]
Thank you :heart:

**Comment by ldez** [comment]
The PR https://github.com/go-critic/go-critic/pull/1280 has changed the `Warning` struct to replace `Node ast.Node` with `Pos token.Pos`.

But in golangci-lint we were using `Node` to manage fix/replacement.

https://github.com/golangci/golangci-lint/blob/ba76af423f3e8feec79ce0a575a9cd72708b75fd/pkg/golinters/gocritic.go#L187

Do you have a suggestion to help me to move quicker on this point?

**Comment by ldez** [comment]
I think [this commit](https://github.com/golangci/golangci-lint/pull/3616/commits/9a265dedf8ff748530603f274e1fbe675fdec7f3) will fix the problem.

**Comment by cristaloleg** [comment]
So, looks like you've fixed on `golangci-lint` side and nothing should be fixed on `go-critic` side, right?

**Comment by ldez** [comment]
yes I fixed it on the golangci-lint side.

Thank you for answering.
