### ISSUE TITLE
httpNoBody: also warn on using "nil" instead of "http.NoBody" on (net/http/httptest).NewRequest

### ISSUE THREAD

**Issue by leonklingele** [go-critic/go-critic#1344]
Currently, no warning is issued when using `nil` instead of `http.NoBody` as a third argument to `(net/http/httptest).NewRequest`.

**Comment by cristaloleg** [comment]
Nice catch, feel free to make a PR 😉

**Comment by leonklingele** [comment]
@cristaloleg updated, ptal! :)

**Comment by leonklingele** [comment]
Implemented with https://github.com/go-critic/go-critic/commit/d97daec322cfc23aacf0d81d429fc9d4cdce5627.
