### ISSUE TITLE
Upgrade to golang 1.22

### ISSUE THREAD

**Issue by muhammad-habib** [go-critic/go-critic#1405]
Based on the GO release policy go1.18 is out of support now

**Comment by Afterous** [comment]
@muhammad-habib , there might be some confusion with regarding go1.18 in the go.mod file.

The [version in the go mod is the semantic version](https://go.dev/doc/modules/gomod-ref#go), so:
- To build the project you need at least go1.18 (using go1.22 complier will work just fine)
- If the project starts to use features that are in higher version such as [the slices package introduced in go1.21.0](https://pkg.go.dev/slices@go1.21.0). That is when the go.mod file will be updated.

I hope this helps!

**Comment by cristaloleg** [comment]
Closing as no-op/no-answer. Thanks.
