### ISSUE TITLE
all: go get fails

### ISSUE THREAD

**Issue by weeellz** [go-critic/go-critic#144]
When installing linter `go get -u github.com/PieselBois/kfulint/...` 
error occurs
`git submodule update --init --recursive
fatal: No url found for submodule path 'vendor/github.com/Quasilyte/astcmp' in .gitmodules
package github.com/PieselBois/kfulint/...: exit status 128`

**Comment by Quasilyte** [comment]
I'll take a look tomorrow.
Thanks for opening an issue for it.

**Comment by Quasilyte** [comment]
Should work now.

**Comment by fexolm** [comment]
@Quasilyte, yes, it works. Thank you for fixing it.
