### ISSUE TITLE
cmd/makedocs: impove error message for "checker docs not found" case

### ISSUE THREAD

**Issue by Quasilyte** [go-critic/go-critic#148]
If new checker misses docs, `cmd/makedocs` will generate empty documentation section for it without warning. Should probably tell something like "can't find docs for XYZ".

**Comment by Quasilyte** [comment]
Weee-eel, maybe it should be left untouched for a little while to make first contribution for someone easier?

**Comment by fexolm** [comment]
@Quasilyte, maybe. It's not so critical.

**Comment by Quasilyte** [comment]
@fexolm, not it doesn't warn or fail if doc comment is missing.
It adds empty documentation for the checker.
I don't mind generating empty (stub) docs for checker that misses proper documentation, but maybe we should emit a warning if there is no `//!` comment inside checker file.

**Comment by Quasilyte** [comment]
Updated original message.

**Comment by Quasilyte** [comment]
Irrelevant now.
