### ISSUE TITLE
all: design and implement debug mechanisms

### ISSUE THREAD

**Issue by quasilyte** [go-critic/go-critic#15]
Debug or verbose mode would be nice.
Don't know what exactly fits our project the best.
Keeping this issue as a reminder.

**Comment by cristaloleg** [comment]
Adding different levels of logging might be enough. WDYT?
Should we also add cpu/mem profile in this task?

**Comment by Quasilyte** [comment]
At the very least we should define what we're going to log and what we are **not** going to log.
Also more concerned about recently found bugs to concentrate on this.
