### ISSUE TITLE
all: complete transfer to new org and repo

### ISSUE THREAD

**Issue by Quasilyte** [go-critic/go-critic#153]
Update docs and all other things.

☑ fix import paths
☑ ensure ci-pr works
☑ ensure ci-push works
☑ update readme (including URLs in badges)

**Comment by fexolm** [comment]
@Quasilyte, done?

**Comment by Quasilyte** [comment]
I don't know. I haven't performed any good investigation on what else needs to be done.
If you have additions, edit original (first) message with empty checkbox. Thank you.
