### ISSUE TITLE
site: create "go-critic.github.io"

### ISSUE THREAD

**Issue by Quasilyte** [go-critic/go-critic#154]
This site should host documentation and project overview.
The URL will be [https://go-critic.github.io/](https://go-critic.github.io/).

**Comment by Quasilyte** [comment]
All site-related issues will go to that new repo.

**Comment by fexolm** [comment]
@Quasilyte closing?

**Comment by Quasilyte** [comment]
The site is (kind of) empty, but it's technically "created".
We can have other issues on it's own repo, you're right.

**Comment by cristaloleg** [comment]
We can add `site` label and just mark new issue.

**Comment by Quasilyte** [comment]
That's an option too.
Could be simpler to maintain issues this way.
I don't have a strong opinion on this, can we can do either way.
