### ISSUE TITLE
all: figure-out project name and logo

### ISSUE THREAD

**Issue by Quasilyte** [go-critic/go-critic#17]
kfulint is a working name, not a final one.
When we know which name we like, it would be a time to find logo (or mascot).

<s>We may also want to rename organization.. For reasons.</s>
We also need a new organization that is dedicated for Go linter only.

**Proposed organization names:**
* Infrared October (repo/org `infrared-october`)
* multilint (repo/org `go-multilint`)
* critic, critique, gritic, critig, crigeek (repo/org with "go-" prefix)
* adviser/advisor/advicer (repo/org with "go-" prefix)

**Comment by weeellz** [comment]
@Quasilyte, how about "Infrared October" as organization name?

**Comment by Quasilyte** [comment]
@weeellz can you explain what "Infrared October" is? :)

**Comment by weeellz** [comment]
@Quasilyte, it means that our sincere desire is to bring the moment of techonological singularity a little bit closer through helping Go programmers write pure code. And it's sounds cool and catchy in my humble opinion.
(how can i be more serious :D)

**Comment by Quasilyte** [comment]
@weeellz, we can collect multiple options and then do a final choice collectively.
Even better, final decision should be made with on-site meeting, so we can discuss it interactively.

**Comment by fexolm** [comment]
SGTM

**Comment by fexolm** [comment]
We could migrate to new organization on saturday I think.

**Comment by weeellz** [comment]
SGTM too/

**Comment by Quasilyte** [comment]
@cristaloleg, you can participate too. ;)

**Comment by cristaloleg** [comment]
```
critic, critique, gritic, critig, crigeek
```
/shrug

**Comment by cristaloleg** [comment]
Hm...or even simpler: `adviser, go-adviser`.
Or we can be unique and don't collide with other names: `advicer, go-advicer`
(yeah, a small reference to https://github.com/cristaloleg/go-advices 😂  )

**Comment by Quasilyte** [comment]
We still need project logo. It will be used as org image as well as included in README.
Everyone who has ideas can share them here.

Most Go projects have gophers in their logo, for example: https://github.com/go-gophers.
![image](https://user-images.githubusercontent.com/6286655/41066633-28204448-69eb-11e8-801b-d887b63abc45.png)

**Comment by Quasilyte** [comment]
@fexolm interesting! Thanks.

**Comment by Quasilyte** [comment]
We have a nice logo now.
