### ISSUE TITLE
lint: consider to skip(`_`) unused parameter

### ISSUE THREAD

**Issue by cristaloleg** [go-critic/go-critic#208]
Name: `unusedParams`
before:
```
func f(a int, b float64) // b isn't used
```
after:
```
func f(a int, _ float64) // everything is cool
```

**Comment by Quasilyte** [comment]
Good, too. I think `go/types` has info about usages, might be useful to determine whether param is being used or not.

**Comment by Quasilyte** [comment]
Looks like one from https://github.com/cristaloleg/go-advices :)

**Comment by cristaloleg** [comment]
Yes, it's :)
