### ISSUE TITLE
all: announcement plans

### ISSUE THREAD

**Issue by Quasilyte** [go-critic/go-critic#218]
This issues is used to track actions we may want to perform to make it possible (and easy) for gophers to find our project. In other words, this is a tracking issue for our public announce.

☑  send PR to [awesome-go-linters](https://github.com/golangci/awesome-go-linters)
☑ send PR to [awesome-go/code-analysis](https://github.com/avelino/awesome-go#code-analysis)
☑ spawn reddit/HN thread
☑ post in https://lobste.rs/
☑ publish https://habr.com article about go-critic + make English translation

Any additions/ideas are welcome.

**Comment by Quasilyte** [comment]
Note: we're not started doing this yet.
It's a discussion and planning for now.

**Comment by Quasilyte** [comment]
CC @fexolm, @cristaloleg, @weeellz, @bontequero, @ludweeg

**Comment by cristaloleg** [comment]
And also: [Awesome Go: Code Analysis](https://github.com/avelino/awesome-go#code-analysis)

**Comment by Quasilyte** [comment]
@cristaloleg, good idea. Updated original message.

**Comment by cristaloleg** [comment]
Some other news feeds:
[r/golang](https://www.reddit.com/r/golang/)
possibly more general [r/programming](https://www.reddit.com/r/programming/)
and yet another(lessy offtopic) HN alternative [lobste.rs](https://lobste.rs/)

**Comment by Quasilyte** [comment]
@cristaloleg, I've never heard of lobste-rs before.
May worth a try.
By the way, are you interested in joining this mission and posting, for example, in reddit/lobsters?

**Comment by cristaloleg** [comment]
Sure, why not?

**Comment by jirfag** [comment]
https://github.com/golangci/awesome-go-linters

**Comment by cristaloleg** [comment]
But it's a first in the original message 😉

**Comment by jirfag** [comment]
sorry, didn't see it :)

**Comment by Quasilyte** [comment]
https://news.ycombinator.com/item?id=17360194
https://habr.com/post/414739/
https://medium.com/@olegkovalov/welcome-go-critic-a26b6e30f1c6
