### ISSUE TITLE
lint/boolFuncPrefix: consider to name bool functions with `Is` prefix

### ISSUE THREAD

**Issue by cristaloleg** [go-critic/go-critic#230]
name: `boolFuncPrefix `
before:
```go
func Enabled() bool
```
after:
```go
func IsEnabled() bool
```

**Comment by Quasilyte** [comment]
I don't think this is very well established convention in go.
There are many examples from stdlib and IIRC, style guides almost explicitly tells that `Is`/`Get`/`Set` prefixes in go are OK, but not enforced on convention level (therefore, it's acceptable to omit that prefix).
Also, sometimes bool returning functions can be named as `ContainsXX`, `HasXX`, etc.

**Comment by Quasilyte** [comment]
For example, `strings.HasPrefix`.
It would be awkward to name that `strings.IsHasPrefix` in my opinion.

**Comment by cristaloleg** [comment]
We can add few exceptions, as you've mentioned: `Has`, `Contains`, whatever.
Maybe it's just me, but from `func Enabled() bool` I will expect `func Enabled() SomeStruct` rather a boolean type.
Same for `func SyntaxOnly() bool` 😉

**Comment by Quasilyte** [comment]
struct is a value.
bool is a value too.
`SyntaxOnly` returns boolean value.
:)

**Comment by cristaloleg** [comment]
Yeah, now it's more clear for me :trollface: 
But anyway, `Is<Smth>() bool` is a well defined and used pattern(same for `Has`, `Have`, `Contains`).

**Comment by Quasilyte** [comment]
You may send a PR that renames `Rule.Experimental` and `Rule.SyntaxOnly` to have `Is` prefix.

But I'm not sure this checker idea is generally implementable without too much false positives.
If you're eager to invest your time into that, then no problems.

**Comment by cristaloleg** [comment]
Roger that

**Comment by Quasilyte** [comment]
We may need `VeryOpinionated` attribute for some rules.

**Comment by Quasilyte** [comment]
`unexportedCall` is one of the existing checks that needs this attribute.

**Comment by cristaloleg** [comment]
I think we can stick to `Experimental` and do not create yet another level of abstraction atm.

**Comment by Quasilyte** [comment]
Can work too. At least for now.
