### ISSUE TITLE
lint: ensure SyntaxOnly checkers can't use types.Info

### ISSUE THREAD

**Issue by quasilyte** [go-critic/go-critic#231]
When checker marked as SyntaxOnly tries to access types.Info from context,
it should panic to make this contract violation apparent.

See also https://github.com/go-critic/go-critic/pull/229.

**Comment by cristaloleg** [comment]
Do you've any ideas how to implement this?

**Comment by Quasilyte** [comment]
Yes, at least 2. But I don't like either of them that much.
