### ISSUE TITLE
all: ability to not scan autogenerated files

### ISSUE THREAD

**Issue by cristaloleg** [go-critic/go-critic#247]
We should easily ignore generated go files(with `DO NOT EDIT` label at the top), in particular we might be also interested in ignoring `protobuf` files.

**Comment by Quasilyte** [comment]
Good idea.
Maybe we need to have a flag that will disable this behavior if someone wants to lint auto-generated files?

**Comment by cristaloleg** [comment]
I think we can add and safely enable `-ignoreGenerated` flag

**Comment by Quasilyte** [comment]
@cristaloleg, sounds reasonable.
