### ISSUE TITLE
cmd/lintwalk: report issue if GOPATH contains multiple paths

### ISSUE THREAD

**Issue by Quasilyte** [go-critic/go-critic#278]
Instead of crashing, `cmd/lintwalk` should report a problem when `GOPATH` contains multiple paths and then exit.

**Comment by Quasilyte** [comment]
Properly supporting multi-GOPATH is also a solution.
But we need a motivated volunteer for that. :)

**Comment by fexolm** [comment]
@Quasilyte, add multi-GOPATH support is not a problem, I could do it if it's necessary.

**Comment by Quasilyte** [comment]
Testing this feature support is more of a concern here.

We're not using multi-GOPATH normally, so without tests it may break unexpectedly at some point.
You may add support for it, if you're willing to test it works properly at least for the moment this feature is implemented.

**Comment by Quasilyte** [comment]
We have many other little things that needs attention, but if this one attracts you, go for it. :)
