### ISSUE TITLE
cmd/makedocs: add tests for generated output validation

### ISSUE THREAD

**Issue by quasilyte** [go-critic/go-critic#296]
It's tedious to check `overview.md` manually.

At the very least we should test that documentation comment is parsed correctly, without extra
whitespace and other artifacts.

It would be also good to test for expected errors to make sure invalid doc comments are rejected.

**Comment by Quasilyte** [comment]
We need to discuss alternative approach for documentation proposed in #322.

**Comment by Quasilyte** [comment]
CC @cristaloleg, @fexolm

**Comment by cristaloleg** [comment]
> without extra whitespace and other artifacts.
is this soooo critical? 😉 

I understand - perfect documentation is sweet, but having small and minor problems is ok.
At least we have docs and they're up to date.

Having test for docs is an overkill.

**Comment by Quasilyte** [comment]
This is not about that.
Please take a look at what PR does.
