### ISSUE TITLE
lint: consider marking paramTypeCombine as opinionated

### ISSUE THREAD

**Issue by Quasilyte** [go-critic/go-critic#297]
Got several requests for that.
Needs discussion.

Maybe we need some kind of evaluation poll that may guide us, so we apply "opinionated" tag properly?
For example, if there are more than 25% votes "against", we mark it as opinionated?

**Comment by Quasilyte** [comment]
It's also been noted that style checks are almost all subjective by their nature.
I see two ways to handle this:
1. Style checks should be in their own category, perhaps? Complicates things as I don't know how `opinionated` and `style` tags would co-exist. Are there any non-opinionated style checks at all?
2. Just consider everything with wide acceptance (not less 75%?) as non-opinionated, even if it's a style check. (`go lint` is unique here as it does **enforces** style constraints, we can't and shoundn't do that, but we could regard code style considered as more idiomatic as a candidate for a style check without `opinionated` tag).

**Comment by fexolm** [comment]
SGTM.
