### ISSUE TITLE
tracking contributions to other repos [UNCLOSABLE ISSUE]

### ISSUE THREAD

**Issue by cristaloleg** [go-critic/go-critic#315]
This issue is to propose projects for code audit with `go-critic`
and share links to already sent pull requests.

Why?
- Detect false positives and bugs in our linter.
- Potentially make other open source projects better.
- Good way to check what checks receive most rejections. We can mark them as `opinionated`.

Outgoing PRs:
https://github.com/shurcooL/markdownfmt/pull/43
https://github.com/mvdan/sh/pull/253
https://github.com/mvdan/sh/pull/254
https://github.com/mvdan/sh/pull/255
https://github.com/afiskon/go-elector/pull/1
https://github.com/rumyantseva/go-zeroservice/pull/3
https://github.com/LK4D4/vndr/pull/73
https://github.com/mamal72/golyrics/pull/2

Projects proposed for contributions:
https://github.com/intel-go/nff-go

**Comment by Quasilyte** [comment]
Doesn't seem to be very useful issue.

**Comment by cristaloleg** [comment]
:(
