### ISSUE TITLE
lint: do not compare float variable directly

### ISSUE THREAD

**Issue by cristaloleg** [go-critic/go-critic#414]
Name: `floatCompare` ?
Before:
```go
var a, b float64 = 10.0, 20.0
return a == b // might be a problem with a precision
```
After:
```go
var a, b float64 = 10.0, 20.0
return math.Abs(a - b) < eps // or any other proper comparison
```

We might also be interested in cases like `x != math.NaN()` that should be written as `math.IsNaN(x)`

**Comment by Quasilyte** [comment]
I think `>` and `<` are somewhat OK for floats, but `==` and `!=` are not.

**Comment by cristaloleg** [comment]
Yep, you're right. `==` and `!=` are more interesting.
