### ISSUE TITLE
lint/underef_checker.go improve output for functions

### ISSUE THREAD

**Issue by fexolm** [go-critic/go-critic#45]
right now for that input
`(*t).a()`
we would show that output
`t.a`
but it should be `t.a()`
(also, don't forget that function could have arguments)

**Comment by fexolm** [comment]
We could also print all statement containing dereference.
To do so we could walk throw function statements and for each statement try to simplify it changing ast (it would also be helpful to quickfix it). If simplified statement wouldn't be equal to original we should warn.

**Comment by Quasilyte** [comment]
Now I think doing several replacements in a row makes interpreting warning message harder.
Maybe it's not worth it?

**Comment by Quasilyte** [comment]
I also think that for function calls it's OK to print undereferenced function expression without arguments.
Arguments only add a noise for warning message.
