### ISSUE TITLE
all: performanceAttribute

### ISSUE THREAD

**Issue by cristaloleg** [go-critic/go-critic#459]
We might be interested into grouping checkers under this attribute, it will allows users to see what checkers can suggest performance improvements.
Also we might add cmd flag for those checkers also.

**Comment by Quasilyte** [comment]
I had such idea before but @fexolm convinced me that we don't need them.

**Comment by cristaloleg** [comment]
Any arguments?

**Comment by Quasilyte** [comment]
I've CCed him. I don't remember myself.

**Comment by Quasilyte** [comment]
Actually, now I think that performance-related checks should be disabled by default and should require `withPerformance` flag to be activated.

**Comment by Quasilyte** [comment]
@cristaloleg, what do you think?

**Comment by cristaloleg** [comment]
👍

**Comment by cristaloleg** [comment]
Resolved in #652
