### ISSUE TITLE
Plans for 0.3.5

### ISSUE THREAD

**Issue by quasilyte** [go-critic/go-critic#482]
Follow-up of #347.
When we finish with 0.3.4, we should know where we're heading next.
Everyone is encouraged to leave a voice here.

> Note that we have 2 chats: [English](https://t.me/joinchat/DWka6g9VbCADtJI5J5w8nQ) and [Russian](https://t.me/joinchat/DWka6kba5sa_EwTgmd3Vng) ([Telegram website](https://telegram.org/)).
Join us there if you want more interactive discussion or have any questions.

Current milestone status (0.3.4): https://github.com/go-critic/go-critic/milestone/7

**Comment by cristaloleg** [comment]
Closing as we already have v0.5.6 :)
