### ISSUE TITLE
criticize: allow to check single file

### ISSUE THREAD

**Issue by dmirogin** [go-critic/go-critic#486]
Like this
`gocritic check-file main.go`

**Comment by Quasilyte** [comment]
SGTM.
Should work for self-contained files.

As a hack that does not require `check-package` to change, we can copy a file into tmp dir, make it a proper package, and then check that package with `check-package`.
This way, we can implement `check-file` as a separate and independent sub-command.
Makes experimenting easier without making `criticize` more complex.

**Comment by dmirogin** [comment]
@cristaloleg I think on first step we can simply check file without loading or somehow hacking declarations inside package.

As @Quasilyte said above, it allows to run gocritic easier to testing and trying something new.

**Comment by Quasilyte** [comment]
> What about not elf-contained files?

I like this typo.

**Comment by quasilyte** [comment]
For quite a long time, it's possible to run gocritic over a single file target. :)
