### ISSUE TITLE
cmd/lintwalk: solve flag forwarding issue between check-package and check-project

### ISSUE THREAD

**Issue by quasilyte** [go-critic/go-critic#505]
Both sub-commands should have same base set of flags (`-withOpinionated`, etc.).

Flag duplicating starts to become a maintenance burden. Maybe there is a better way.

**Comment by cristaloleg** [comment]
What about creating a `flags` package in `cmd` which will be responsible for flag parsing and validation?

**Comment by Quasilyte** [comment]
That's one of the options.
But lets not be too hasty about it.

**Comment by cristaloleg** [comment]
Sure, just proposing atm.

**Comment by ewgRa** [comment]
Can I take this? For me proposal about shared flags package looks easiest and actually I don't see a problems there, other options probably will be excessive at this moment.

In case if there is will be better solution it will be easy to refactor, package will be well isolated.

btw, what is another options? I see only some cli-specialized library like https://github.com/jessevdk/go-flags. Any other options?

**Comment by cristaloleg** [comment]
"flag" from stdlib, why not?

**Comment by Quasilyte** [comment]
> Can I take this?

Sure.
