### ISSUE TITLE
lint: detect "if err == nil { return err }"

### ISSUE THREAD

**Issue by quasilyte** [go-critic/go-critic#524]
Detects suspicious nil error return.

**Before:**
```go
if err == nil {
	return err
}
```
**After:**
```go
// (A)
if err != nil {
	return err
}
// (B)
if err == nil {
	return nil
}
```

**Comment by Quasilyte** [comment]
Or should it be handled along with #432?

**Comment by cristaloleg** [comment]
Think we can merge it with #432 . It will harm no one, imo.

**Comment by Quasilyte** [comment]
It depends on the implementation.
Lets keep this one open until we have one.

**Comment by cristaloleg** [comment]
Example from https://github.com/moby/moby/pull/37551
