### ISSUE TITLE
lint: detect RLock+Unlock

### ISSUE THREAD

**Issue by quasilyte** [go-critic/go-critic#548]
Detects unmatched lock+unlock calls.

**Before:**
```go
mu.RLock()
defer mu.Unlock() // Should be RUnlock
```

**After:**
```go
mu.RLock()
defer mu.RUnlock()
```

**Comment by cristaloleg** [comment]
This can be extended to any combination lock-unlock funcs, so `Lock` & `RUnlock`

**Comment by Quasilyte** [comment]
Yep. The point is mismatching lock+unlock pairs.

**Comment by Quasilyte** [comment]
Idea comes from @corylanou speech about "concurrency in Go" from gophercon UK.

**Comment by breml** [comment]
I asked myself, if this could be even more extended, such that we find, if a write happens, but only a read lock was obtained. E.g.

```go
d.mu.RLock()
m.data[key] = value
m.mu.RUnlock()
```

The thing is, we do not really know, what is protected by the lock (especially, if the code is more complicated than the example above).

**Comment by cristaloleg** [comment]
I thought about this long time ago, and afair there are 2 most common cases.
1. 
```go
type A struct {
	m sync.Mutex
	// fields
}
```
And we should check all the fields to be in sync.

2. 
```go
type A struct {
	// fields

	m sync.Mutex
	// other fields
}
```
And we should check only 'other fields' 'cause this pattern is suggested in Effective Go (or in some other standard document).

But also all this cases can be easily verified by race detector 🤔

**Comment by quasilyte** [comment]
@cristaloleg, I think that's too much for a single check. We could do several checks for locks.

**Comment by quasilyte** [comment]
We don't handle complex cases, but simple cases are covered by #999

**Comment by quasilyte** [comment]
Let's close this issue and if any improvements are required, we can open a new one.
