### ISSUE TITLE
lint: mark builtinShadow as obsolete?

### ISSUE THREAD

**Issue by Quasilyte** [go-critic/go-critic#565]
We might want to remove `builtinShadow` checker support at some time.
(See https://github.com/dominikh/go-tools/commit/32683e82cecec724fb6f82a9d00acfe072bad196.)

It may be a worthwhile to maintain a page where we list checks that were marked as obsolete due to implementation in other linters (at least in ones that are included into gometalinter).

**Comment by Quasilyte** [comment]
CC @cristaloleg

**Comment by cristaloleg** [comment]
Sounds reasonable 👍
