### ISSUE TITLE
Question regarding removing checks

### ISSUE THREAD

**Issue by iggyzap** [go-critic/go-critic#566]
Hi,

Just wonder how often do you plan on deprecating and removing checks ?

Also another question - have you seen wide adoption of your checks in other linters ?

With regards,
Ignat Zapolsky

**Comment by Quasilyte** [comment]
Hello, @iggyzap.

> Just wonder how often do you plan on deprecating and removing checks ?

We had 0 occasions so far, but at least 1 is going to happen in some near future.
See #565.

> Also another question - have you seen wide adoption of your checks in other linters ?

Hard to tell. 
Maybe 1 check was adopted, but it can be a coincidence that is unrelated to gocritic at all (see issue referenced above).

It's hard to track many other linters, but what I try to do is checking ones that are included into `gometalinter`. If some check is already there, it's unlikely that it will be included into gocritic. If it gets implemented afterwards, there is a possibility that a check will be marked as obsolete and removed from gociritc, but this process is not yet decided and there can be tough cases.
(It does matter which linter did the adoption.)

It would be easier to answer your question if you could provide some more info.
For example, it's unclear why do you ask this.

Thanks.

**Comment by dominikh** [comment]
https://github.com/dominikh/go-tools/issues/305 might be of interest.

**Comment by iggyzap** [comment]
Hi @Quasilyte ,

Thank you for your prompt response.

At the moment we are evaluating different linters for golang for ci application, and one of the questions regarding if go-critic can be used is how stable it is, i.e. how much notice will be given when some checks will be removed so we can adjust tool chain.

On the other hand, since we probably won't re-build the linter for every analysis, this is more academic question (and we will be using pre-build tool).

Since you already mentioned that you want to have a page that'll list deprecated checks that will be removed in the future, I think this is a good start and provides a good forewarning for changes.

With regards,
Ignat Zapolsky.

**Comment by cristaloleg** [comment]
Closing the issue as an old and inactive. Feel free to ping us.
