### ISSUE TITLE
config option work against user experience

### ISSUE THREAD

**Issue by ewgRa** [go-critic/go-critic#570]
If I run "go run main.go check-package -config a.json fmt" with empty a.json file, I'm expected that no any checkers will be used. There is expectations, that config file also configure checkers, that I want to run.

For now there is unexpected "default" checkers runs.

How about made changes close to user experience and config will be really config?

**Comment by Quasilyte** [comment]
It sounds good to me that there should be a way to configure enabled set via the config.
@cristaloleg, what do you think?

**Comment by cristaloleg** [comment]
Yep, good one.

**Comment by ewgRa** [comment]
closed in #573
