### ISSUE TITLE
Cannot be installed with Go modules enabled

### ISSUE THREAD

**Issue by mastertinner** [go-critic/go-critic#598]
Trying to install this tool with Go modules enabled fails:

```shell
$ GO111MODULE=on github.com/go-critic/go-critic/...
go: cannot find main module; see 'go help modules'
```

I think to solve that, we need to make it a Go module by adding a `go.mod` file.

**Comment by Quasilyte** [comment]
I think the full command was:
```
GO111MODULE=on go get -u github.com/go-critic/go-critic/...
```
I can reproduce the issue, thanks for reporting.

**Comment by Quasilyte** [comment]
> I think to solve that, we need to make it a Go module by adding a go.mod file.

Yep, that's right.

**Comment by cristaloleg** [comment]
@mastertinner fixed in https://github.com/go-critic/go-critic/pull/600
Everything should work from now, thanks for noticing 😉

**Comment by mastertinner** [comment]
Yes, it works now. Thanks a lot for the quick fix!
