### ISSUE TITLE
installation

### ISSUE THREAD

**Issue by Konstantin8105** [go-critic/go-critic#619]
In according to README:
```
Installation
go get -u github.com/go-critic/go-critic/...
```
Please clarify about next steps.
As I understood, next step is:
```
cd $GOPATH/github.com/go-critic/go-critic
make install
```

**Comment by dominikh** [comment]
https://golang.org/doc/code.html#remote

**Comment by cristaloleg** [comment]
No, you don't need to make additional steps to star using go-critic.
Go-getting it is enough.

`make install` is a dev command, to install go-critic from source, for easier testing 😄

**Comment by Konstantin8105** [comment]
Excuse, it is my confuse. Name of  project gihub is `go-critic`, but app name `gocritic`.
Thank you.

**Comment by cristaloleg** [comment]
No problem, have a good day 😉
