### ISSUE TITLE
lint: rename unusedParam to blankParam

### ISSUE THREAD

**Issue by Quasilyte** [go-critic/go-critic#635]
If we're keeping this checker, it should be renamed in order to avoid confusion.
"unusedParam" sounds like something that `unused` linter from staticcheck would do.
"blankParam" is as precise, but avoids that confusion.

See also #516

**Comment by Quasilyte** [comment]
CC @cristaloleg

**Comment by cristaloleg** [comment]
SGTM

**Comment by Atul9** [comment]
@Quasilyte @cristaloleg I would like to work on this
