### ISSUE TITLE
Unify checkers test package names

### ISSUE THREAD

**Issue by Quasilyte** [go-critic/go-critic#669]
Some packages use `checkers_test` and others use `checkers_tests`.
Should probably go with either one consistently in all `lint/testdata` tests.

Seems like plural form is less frequent:
```
$ grep -nr 'package checker_test$' | wc -l
91
$ grep -nr 'package checker_tests$' | wc -l
24
```

**Comment by Quasilyte** [comment]
@gteshome, yes.

**Comment by gteshome** [comment]
I see @alimasyhur already submitted the PR so I won't submit mine.
