### ISSUE TITLE
Windows: Can't create temp directory if parents missing

### ISSUE THREAD

**Issue by dertseha** [go-critic/go-critic#671]
It seems that the creation of the temporary directory does not include its parents under Windows:

```
P:\go\src\github.com\inkyblackness\imgui-go>gocritic.exe check-project .
mkdir C:\Users\<username>\AppData\Local\Temp\github.com\inkyblackness\imgui-go_C751490923: The system cannot find the path specified.
load program: couldn't load packages due to errors: github.com\inkyblackness\imgui-go
lint error: exit status 1
```
Only after manually creating `C:\Users\<username>\AppData\Local\Temp\github.com\inkyblackness\`, gocritic works.

**Comment by Quasilyte** [comment]
Since we're now using [packages](https://godoc.org/golang.org/x/tools/go/packages) and there is no separate command for checking `project` anymore, this issue is probably out of date.

You can now run:
```bash
gocritic check .
```
Instead of:
```bash
gocritic check-project .
```
