### ISSUE TITLE
lint: singleCaseSwitch and inner "break" statements

### ISSUE THREAD

**Issue by quasilyte** [go-critic/go-critic#682]
If single case `switch` contains a `break`, it can't be trivially re-written to `if`.
Right now, `singleCaseSwitch` checker ignores the statement body. It should check whether that body contains any `break` that belongs to the enclosing `switch` statement.

**Comment by breml** [comment]
@Quasilyte to better understand this bug, it would be helpful to have an example, which shows, why in this case it is not easy to rewrite the respective `switch` statement.

**Comment by Quasilyte** [comment]
Oh, sure.
Here is very simplified case:
```go
func before(xs []interface{}) {
	for _, x := range xs {
		switch x.(type) {
		case int:
			fmt.Println(x)
			break
		}
	}
}

func after(xs []interface{}) {
	for _, x := range xs {
		if x, ok := x.(int); ok {
			fmt.Println(x)
			break
		}
	}
}
```
It's possible to see the problem here, but if case body is big and contains several conditionals, it will be hard to detect whether "break" should be removed as well.
