### ISSUE TITLE
lint: add negative tests for typeSwitchVar

### ISSUE THREAD

**Issue by Quasilyte** [go-critic/go-critic#684]
There are only [positive tests](https://github.com/go-critic/go-critic/blob/master/lint/testdata/typeSwitchVar/positive_tests.go) for the `typeSwitchVar` checker.
There should be at least some negative tests that verify that it doesn't trigger on the simplified type switches.

**Comment by GaryPWhite** [comment]
I'm on it!

**Comment by agneum** [comment]
I've added some negative tests. Please check the PR: https://github.com/go-critic/go-critic/pull/688
