### ISSUE TITLE
lint: detect empty lines at the beginnings and endings of blocks

### ISSUE THREAD

**Issue by AlekSi** [go-critic/go-critic#690]
The first block line is empty – warning:
```go
func foo() {

    bar()
}
```

The last block line is empty – warning:
```go
if baz {
    foo()

}
```

The first line is a comment – fine:
```go
func foo() {
    // foo is baz so foobar

    bar()
}
```

**Comment by AlekSi** [comment]
Oh, revive added this. https://github.com/mgechev/revive/pull/81 Probably can be closed. :)

**Comment by Quasilyte** [comment]
@AlekSi, OK. :)
