### ISSUE TITLE
checkers: handle "//export" comment in commentFormatting checker

### ISSUE THREAD

**Issue by quasilyte** [go-critic/go-critic#724]
Comments like `//export Foo` should not trigger a warning.
See https://golang.org/cmd/cgo/#hdr-C_references_to_Go.

**Comment by sni** [comment]
any news on this?

**Comment by quasilyte** [comment]
It should be fixed now. :)

For some reason, I forgot to set the "good first issue" label. It was supposed to be a great low-hanging fruit for first-time contributors. But I guess waiting for 2 years is enough.

**Comment by sni** [comment]
thanks a lot
