### ISSUE TITLE
checkers: defined errors instead fmt.Errorf

### ISSUE THREAD

**Issue by saromanov** [go-critic/go-critic#777]
Hi Iskander and other maintainers! Thanks for you project, there is great idea! Do you have a plans to add checker for errors like this?

```go
fmt.Errorf("some error without format)
```

to this
```go
var myError = errors.New("some error without format")
```

I think `fmt.Errorf` not make sense without arguments and it should be moved to defined errors. What do you think?

**Comment by cristaloleg** [comment]
Looks like it's already implemented, please see: https://github.com/go-critic/go-critic/issues/473#issuecomment-406989230

**Comment by cristaloleg** [comment]
Yeah, it says `emptyFmt` because there is no params to the formatting function (like `Errorf`, `Printf`, `Fatalf`, so on).

Basically it's a side effect ;D
