### ISSUE TITLE
Initial go get fails

### ISSUE THREAD

**Issue by DryHumour** [go-critic/go-critic#810]
An initial attempt to get go-critic will fail with a git submodule error.  This failure does, however, leave the git clone checked out and a subsequent get will work (presumably because an empty go-critic sub-sub-sub-directory was created by git submodule during the initial clone).
```
$ go get -v github.com/go-critic/go-critic/...
github.com/go-critic/go-critic (download)
# cd /home/nschelle/go/src/github.com/go-critic/go-critic; git submodule update --init --recursive
fatal: No url found for submodule path 'go-critic' in .gitmodules
package github.com/go-critic/go-critic/...: exit status 128
```
My git-fu is weak, but I think the problem is that commit fc92fdb14a33766600962e970854229d0aace500 (or b9373569160643640c0cfa345c5b6c8d549ad36d?) introduced some sort of phantom submodule without a .gitmodules.
```
$ git ls-files --stage | grep 160000
160000 b9373569160643640c0cfa345c5b6c8d549ad36d 0	go-critic
```

**Comment by Helcaraxan** [comment]
This can now be closed I think, @Quasilyte. :slightly_smiling_face:
