### ISSUE TITLE
make CI green again

### ISSUE THREAD

**Issue by Quasilyte** [go-critic/go-critic#812]
Build on master started to fail.

https://travis-ci.org/go-critic/go-critic/jobs/499426168

```
github.com/golang/lint@v0.0.0-20190227174305-5b3e6a55c961: parsing go.mod: unexpected module path "golang.org/x/lint"
```

**Comment by Quasilyte** [comment]
Checking out last successful build (b9373569160643640c0cfa345c5b6c8d549ad36d) doesn't help. Seems like some dependency has changed causing the build to fail.

**Comment by Helcaraxan** [comment]
I have not yet found which dependency but the root cause is golang/lint#397.

Some dependency somewhere must have a deprecated `go.mod` that is referencing `github.com/golang/lint` instead of `golang.org/x/lint`.

**Comment by Quasilyte** [comment]
We could track that dependency and, for example, vendor it, and keep it until upstream is fixed (or it can be better to use specific revision, before it started to cause problems).

@cristaloleg, what is your opinion?

**Comment by Quasilyte** [comment]
https://github.com/go-critic/go-critic/pull/813#issuecomment-468219688

>  @Quasilyte have actually just left a comment there about the root cause. Have not been able to trace the offending dependency yet (no appropriate tooling for that exists yet AFAIK with go modules).

Seems like an idea for a new tool.
I think we should at least ping @myitcv or, better yet, post it on `golang-tools`.
Maybe other people faced the same problem.

**Comment by myitcv** [comment]
Why are you doing `go get -u` here?

https://github.com/go-critic/go-critic/blob/fc92fdb14a33766600962e970854229d0aace500/Makefile#L24

You already have `github.com/go-lintpack/lintpack` as a module requirement, no?

https://github.com/go-critic/go-critic/blob/fc92fdb14a33766600962e970854229d0aace500/go.mod#L4

The `-u` flag here is likely the cause:

> The -u flag instructs get to update dependencies to use newer minor or
patch releases when available. Continuing the previous example,
'go get -u A' will use the latest A with B v1.3.1 (not B v1.2.3).

(from `go help get` in Go 1.12)

**Comment by Helcaraxan** [comment]
@Quasilyte have added the fix to #813.

**Comment by Helcaraxan** [comment]
@myitcv good point indeed. Am new to this project so had not had a look at the script. Thank you very much for the help!

**Comment by myitcv** [comment]
You're welcome!
