### ISSUE TITLE
Annotate returned errors

### ISSUE THREAD

**Issue by breml** [go-critic/go-critic#834]
If I review code, I encurage my coleagues to not just return errors but to annotate them in appropriate form. This can be by wrapping the error with e.g. `fmt.Errorf(..., err)` or if more context is needed with something like [`errors.Wrap(err, ...)`](https://godoc.org/github.com/pkg/errors#Wrap).

If errors end up in e.g. log files, it is generally better to have some additional context, where exactly an error happened, because otherwise log entries with errors e.g. from the standard library are hard to pin to the location in the code, where they occured.

This is request is opinionated, I know. So let us find out, if there is interest to put this in go-critic.

**Comment by quasilyte** [comment]
I got similar requests before.
I have some thoughts on that topic, I'll share them in the near future (need to verify it beforehand).

**Comment by cristaloleg** [comment]
Looks like this is solved in https://github.com/tomarrell/wrapcheck so closing.
