### ISSUE TITLE
checkers: suggest x++ instead of x += 1

### ISSUE THREAD

**Issue by twpayne** [go-critic/go-critic#835]
Currently, given the code:

```go
x = x + 1
```

`go-critic` suggests that this should be replaced with

```go
x += 1
```

`x++` would be a better suggestion. Similarly for `x -= 1` / `x--`;

**Comment by quasilyte** [comment]
Yep, could be done. :)
I wanted to avoid making extra efforts for something that go lint would detect.
Those two cases are not hard to support though.

**Comment by twpayne** [comment]
Thanks very much!
