### ISSUE TITLE
command not found: lintpack

### ISSUE THREAD

**Issue by JerkyTreats** [go-critic/go-critic#855]
I am new to Go, pretty sure Im missing something simple here. 

I've followed Installation instructions, but hit the following:

```
lintpack build -o gocritic -linter.version='v0.3.4' -linter.name='gocritic' github.com/go-critic/go-critic/checkers
zsh: command not found: lintpack
```

Certainly feels like Im missing something obvious, but I've Googled for the past 20 minutes and nothing's leaping out at me.

**Comment by quasilyte** [comment]
I wasn't able to pay attention to this in time.
I hope everything works for you now.
