### ISSUE TITLE
only replace the $GOPATH if to "$GOPATH" if the project resides in $GOPATH

### ISSUE THREAD

**Issue by JAicewizard** [go-critic/go-critic#858]
using a path like ~/go-projects will be replaced with $GOPATH-projects

**Comment by quasilyte** [comment]
You mean that warning message contains a path that starts with `$GOPATH`?
That feature can be disabled with `-shorterErrLocation=false`.

**Comment by JAicewizard** [comment]
The full path for a file would be `/home/jaap/go-projects/project/file.go`
go-critic shortens this to `$GOPATH-projects/project/file.go` because it detects the GOPATH in the path.

Only files located in `$GOPATH` should be shortened not everything that happens to contain `$GOPATH`

**Comment by quasilyte** [comment]
I see. Thanks. Will fix it soon.
