### ISSUE TITLE
Can not compile

### ISSUE THREAD

**Issue by tegk** [go-critic/go-critic#862]
../../../go/pkg/mod/github.com/go-critic/go-critic@v0.3.4/checkers/commentFormatting_checker.go:24:10: undefined: astwalk.WalkerForComment

**Comment by quasilyte** [comment]
Interesting. It's probably because a version tagged in mod file doesn't have that walker yet. I'll take a look, thanks.

**Comment by jtbonhomme** [comment]
Same error here:
```
$ lintpack build -o gocritic -linter.version='v0.3.4' -linter.name='gocritic' github.com/go-critic/go-critic/checkers

build linter: build failed: exit status 2:
# github.com/go-critic/go-critic/checkers
../../../../../../pkg/mod/github.com/go-critic/go-critic@v0.3.4/checkers/commentFormatting_checker.go:24:10: undefined: astwalk.WalkerForComment

$ go version
go version go1.11.6 darwin/amd64

```

**Comment by sourya** [comment]
Somehow, it works when `go get` is called with `-u`, i.e., `go get -u github.com/go-critic/go-critic/...`. I'm not sure why updating the dependencies works, since the version of lintpack used is `v0.5.2`, which has the `astwalk.WalkerForComment` function.

**Comment by cristaloleg** [comment]
Closing as not active (and probably outdated :) Feel free to reopen.
