### ISSUE TITLE
Detect occasions where slice is created without size where the size could be known

### ISSUE THREAD

**Issue by breml** [go-critic/go-critic#874]
Detect occasions, where a new slice is created without size (or with len == 0), where the length could be known.

Before:

```Go
func numbersToStringsBad(numbers []int) []string {
	vals := []string{}
	// or 
	// vals := make([]string, 0)
	// or 
	// vals := make([]string, 0, 0)
	for _, n := range numbers {
		vals = append(vals, strconv.Itoa(n))
	}
	return vals
}
```

After:

```Go
func numbersToStringsBetter(numbers []int) []string {
	vals := make([]string, 0, len(numbers))
	for _, n := range numbers {
		vals = append(vals, strconv.Itoa(n))
	}
	return vals
}
```

Inspired by: [Bad Go: not sizing slices](https://philpearl.github.io/post/bad_go_not_sizing_arrays/)

**Comment by cristaloleg** [comment]
Sounds like a `prealloc` linter https://github.com/alexkohler/prealloc (also a part of a golangci-lint afair)

**Comment by quasilyte** [comment]
I think it's better to leave this to prealloc linter mentioned above.
