### ISSUE TITLE
checker: append to pre-allocated slice

### ISSUE THREAD

**Issue by ashanbrown** [go-critic/go-critic#875]
I've written a small linter called https://github.com/ashanbrown/makezero and I wanted to get feedback about whether it might be worth incorporating it into go-critic.  It addresses the failure to use of append in the example below

```golang
func copyNumbers(nums []int) []int {
  values := make([]int, len(num))
  for i, n := range nums {
    values[i] = n
  }
  return values 
}
```

IMO, the above code looks like it has been written by a C-programmer and it would be written more idiomatically in Go as:

```golang
func copyNumbers(nums []int) []int {
  values := make([]int, 0, len(num))
  for _, n := range nums {
    values = append(values, n)
  }
  return values 
}
```

It tries to encourage the use of `append` using a somewhat indirect, very strict rule, which is that every `make` of an array with a preallocated size must also have initial length 0 (hence it being called `makezero`).  In practice this has worked really well on codebases I've worked on, but I realize that for more data intensive applications that do a lot of copying to preallocated slices, it may not be a great rule.

The reason that the linter encourages append in an indirect way (by requiring an initial length of zero) is that the other thing the linter does is try to prevent the error shown in the code below, where we append to non-empty array:

```golang
func copyNumbers(nums []int) []int {
  values := make([]int, len(num))
  for _, n := range nums {
    values = append(values, n)
  }
  return values 
}
```

In this code, we've failed to set the initial length of the `values` array to zero, and accidentally filled the slice with default `int` values (i.e. 0's), which probably was not what we intended.  The linter -- when it doesn't simply enforce `make` with zero length -- does some rudimentary analysis to see if `append` is being used on the array.  It doesn't look inside structs though (e.g. `x.values = make([]int, 10)` wouldn't be recognized as problem).  I'm not sure this kind of analysis is in go-critic's domain since it's really a heuristic to avoid a bug rather than a style concern.

Would love your thoughts.  Thanks for the fantastic linter.

**Comment by quasilyte** [comment]
For the first two examples. it's debatable because some Go programmers prefer the 1st form in some cases. The second case is also not optimized by the compiler, IIRC. We generally don't want to unconditionally give people advice on how to make code run slower. And it's hard to detect whether that loop lies on the hot path.

Detecting erroneous appends to a slice that had non-zero length is a good thing.

**Comment by ashanbrown** [comment]
Thanks for the feedback.  I'm still not sure that detecting bad appends necessarily fits into gocritic's domain so I'll close this request.
