### ISSUE TITLE
Cannot disable 'dubSubExpr' check

### ISSUE THREAD

**Issue by zodac** [go-critic/go-critic#877]
I've updated by .golangci.yaml to include the following configuration for gocritic:

```
gocritic:
    enabled-tags:
      - performance
      - experimental
      - style
    disabled-checks:
      - dubsubexpr
```

However, when attempting to run the linter (through golangci-lint), I get the following message:
```
WARN Gocritic check "dubsubexpr" was disabled by config, was it's not enabled, no need to disable it
ERRO Invalid gocritic settings: validation failed: disabled checker dubsubexpr doesn't exist, all existing checkers: [appendassign appendcombine argorder assignop badcall badcond boolexprsimplify builtinshadow captlocal caseorder codegencomment commentedoutcode commentedoutimport commentformatting defaultcaseorder deprecatedcomment docstub duparg dupbranchbody dupcase dupimport dupsubexpr elseif emptyfallthrough emptystringtest equalfold evalorder exitafterdefer flagderef flagname hexliteral hugeparam ifelsechain importshadow indexalloc initclause methodexprcall nestingreduce newderef nilvalreturn octalliteral offby1 paramtypecombine ptrtorefparam rangeexprcopy rangevalcopy regexpmust regexppattern singlecaseswitch sloppylen sloppyreassign stringxbytes switchtrue typeassertchain typeswitchvar typeunparen underef unlabelstmt unlambda unnamedresult unnecessaryblock unslice valswap weakcond wrapperfunc yodastyleexpr]
```

The main error being that it seems to not find the checker, even though it is listed:
**disabled checker dubsubexpr doesn't exist, all existing checkers: [... dupsubexpr ...]**

**Comment by dertseha** [comment]
Hello @zodac , I came here semi-randomly.

The checker is listed, and present, as you have found it: du**p**SubExpr .
The checker that you attempted to disable does not: du**b**subexpr .
Classic typo, potentially influenced by music ;)

Also: The name of the checker is case-sensitive, so you have to write `dupSubExpr` (note the capital S and E letters).

**Comment by quasilyte** [comment]
I think you might have a typo there:
```
dubsubexpr
dupsubexpr <- s/dub/dup/
```

**Comment by zodac** [comment]
Haha, worry, very silly on my part. Thought I'd checked that, but must be going crazy, Apologies for the waste of time.
