### ISSUE TITLE
command not found gocritic

### ISSUE THREAD

**Issue by sain801028** [go-critic/go-critic#893]
![螢幕快照_2019-12-02_13-24-36](https://user-images.githubusercontent.com/17377422/69932702-1afd8c80-1507-11ea-9dac-7c4eabfccf46.png)

**Comment by cristaloleg** [comment]
Hi, can you show you `go env` output?

**Comment by sain801028** [comment]
![螢幕快照_2019-12-02_15-40-50](https://user-images.githubusercontent.com/17377422/69939175-2908d880-151a-11ea-98d3-5b5b87b3e40e.png)

**Comment by cristaloleg** [comment]
I suppose it doesn't exist ins `$GOROOT/bin`, so try to make `go get` again

**Comment by quasilyte** [comment]
@cristaloleg why would you need it under `$GOROOT`? Do you mean `$GOPATH`?

Anyway, it should be under a system `$PATH`, the exact binary location doesn't matter. It's just very common to have a "main" `$GOPATH` somewhere around `~/go` and `$PATH` pointing to `~/go/bin`. I think it's possible to set a separate "tools GOPATH" inside VS code, it can be more convenient that having to install all binaries under your current workspace.

I hope that helps.

**Comment by sain801028** [comment]
So what should I do?

**Comment by sain801028** [comment]
![螢幕快照_2019-12-04_10-35-27](https://user-images.githubusercontent.com/17377422/70107577-da764e00-1681-11ea-8c25-9b37fe9e294e.png)

gocritic not work

**Comment by sain801028** [comment]
![螢幕快照_2019-12-04_10-44-28](https://user-images.githubusercontent.com/17377422/70107993-14941f80-1683-11ea-84a7-3c00bc70eeb9.png)

**Comment by sain801028** [comment]
![螢幕快照_2019-12-04_10-47-28](https://user-images.githubusercontent.com/17377422/70108152-89675980-1683-11ea-9998-5d31e099fd31.png)

**Comment by sain801028** [comment]
I have solved
