### ISSUE TITLE
Possible File Corrupt On Save

### ISSUE THREAD

**Issue by johneboldt** [go-critic/go-critic#903]
My Go files are periodically getting corrupted on save and I noticed this error in the console:
```
[Extension Host] Error: Illegal value for `line`
	at h._lineAt (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:391:466)
	at Object.lineAt (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:390:368)
	at c:\Users\JohnBoldt\.vscode\extensions\neverik.go-critic-0.1.0\out\extension.js:36:48
	at Array.forEach (<anonymous>)
	at c:\Users\JohnBoldt\.vscode\extensions\neverik.go-critic-0.1.0\out\extension.js:35:22
t.log	@	console.ts:137
```
Is the error possibly related to the file corruption?

VS Code 1.41.1 on Windows 10

**Comment by cristaloleg** [comment]
Any code example that triggers such error?

**Comment by quasilyte** [comment]
I've noticed that you're using go-critic extension for VSCode.

Please consider using [golangci-lint](https://github.com/golangci/golangci-lint) extension, I believe it's better maintained.

**Comment by johneboldt** [comment]
I have isolated issue to the go extension, so I'm closing this issue. I will try the golanci-lint extension as recommended above.

**Comment by quasilyte** [comment]
In some distant future, transition to go/analisis framework will be completed and it will be easy to use go-critic as one of the gopls plugins (fortunately).
