### ISSUE TITLE
Don't Apply "paramTypeCombine" to multi-line field lists

### ISSUE THREAD

**Issue by tooolbox** [go-critic/go-critic#938]
This is great:
```go
func (a int, b int) int { // ... }
// to
func (a, b int) int { // ... }
```
This is not good:
```go
func(
  a string,
  b int,
  c int,
  d []byte,
) int { // ... }
// to
func(
  a string,
  b, c int,
  d []byte,
) int { // ... }
```
This is a little strange too:
```go
func(
  a string,
  b, 
  c int,
  d []byte,
) int { // ... }
```
My suggestion is having `paramTypeCombine` ignore functions with multi-line param field lists.

I can give a PR if that's acceptable.

**Comment by quasilyte** [comment]
> My suggestion is having paramTypeCombine ignore functions with multi-line param field lists.

This is a good idea.

> I can give a PR if that's acceptable.

It would be the best. :)
