### ISSUE TITLE
Tag a release to fix a broken dependency

### ISSUE THREAD

**Issue by joel0** [go-critic/go-critic#953]
@quasilyte contributed a fix, c61cd34f788cf88e9ccd4f92c9911b86bc01cf60, for a breaking change in ruleguard.  Without this fix, modules that include go-critic with `go get -u` fail to build.  An example is [Hashicorp's Nomad v0.11](https://github.com/hashicorp/nomad/blob/v0.11.4/GNUmakefile#L183) indirectly including go-critic.  I think a patch or minor release with the fix mentioned would be good.

**Comment by quasilyte** [comment]
https://github.com/go-critic/go-critic/releases/tag/v0.5.1

**Comment by joel0** [comment]
Thanks!

**Comment by quasilyte** [comment]
Sorry for the inconvenience.
