### ISSUE TITLE
exitAfterDefer warn message unclear

### ISSUE THREAD

**Issue by josephzidell** [go-critic/go-critic#972]
In https://github.com/go-critic/go-critic/blob/324b43907f3b01a3a77d318660e0ccdc563a1211/checkers/exitAfterDefer_checker.go#L75, the checker finds calls to Fatal in a func that contains a `defer`. However, the warning message says `clutters` which can be confused with literal cluttering. Would you be open to accepting a PR that rephrases it?

**Comment by quasilyte** [comment]
>  Would you be open to accepting a PR that rephrases it?

Sure! It would be great.

The meaning is: "if you're using exit after defer, that defer won't be executed; so you probably don't want to do an exit, or you don't want a defer". Something like this. :)

**Comment by josephzidell** [comment]
@quasilyte Awesome! PR #978 coming your way 👍

**Comment by quasilyte** [comment]
Fixed in #978
