### ISSUE TITLE
framework/linttest: add a special flag to debug a specific file from the testdata

### ISSUE THREAD

**Issue by quasilyte** [go-critic/go-critic#980]
It could be an env var like in go: GOSSAFUNC -> `GOCRITIC_TESTFILE=foo.go`.
This way it's easier to debug new checkers.
We may go further, but this looks like a good start.

After that. we can create a separate file `debug.go` (the name doesn't matter) near the positive and negative test files. When gocritic tests are executed with this flag, only the specified file is analyzed.

Note: it only works for tests. When go-critic will switch to packages as input it won't be easy to support such a feature.

@cristaloleg do you think it could help us in the situation we ended up yesterday? :)

**Comment by cristaloleg** [comment]
Sounds reasonable. Run over `debug.go` only if it's present. `debug.go` -> `positive/negative.go` -> repeat loop sounds pretty good to me.
