### ISSUE TITLE
add security tag

### ISSUE THREAD

**Issue by cristaloleg** [go-critic/go-critic#981]
In the bright future we would like to make more security related checkers, to be able to do this, we need to add such tag. 

Basically 1 liner.

**Comment by DLambros91** [comment]
I could take care of this.

**Comment by cristaloleg** [comment]
@DLambros91 go on

**Comment by servusDei2018** [comment]
The security tag has been added, I suggest this issue be closed.

**Comment by cristaloleg** [comment]
fixed in https://github.com/go-critic/go-critic/pull/989
