### ISSUE TITLE
Make it possible to embed ruleguard rules inside go-critic

### ISSUE THREAD

**Issue by quasilyte** [go-critic/go-critic#994]
An extra requirement: we want the external API to look the same; like the implementation of the checkers hasn't changed at all.

**Comment by orsinium** [comment]
It would be great! [Ruleguard](https://github.com/quasilyte/go-ruleguard) is a beautiful solution to describe simple rules and looks like there is almost no linter that supports writing checks via ruleguard. I found only [semgrep-go](https://github.com/dgryski/semgrep-go), and it has no license (https://github.com/dgryski/semgrep-go/issues/16) nor [golangci-lint](https://github.com/golangci/golangci-lint) integration (https://github.com/dgryski/semgrep-go/issues/15).

**Comment by cristaloleg** [comment]
So, it's done :)
